-- Reemplaza el menú ficticio por el menú real del negocio (verificado en su
-- plataforma de pedidos en línea). No borra nada: usa INSERT ... ON DUPLICATE
-- KEY UPDATE, así que es seguro sin importar qué ids ya existan (repuebla los
-- que ya había y agrega los que falten). Los pedidos y comprobantes ya emitidos
-- guardan su propio snapshot (nombreProducto, precio, datosEmision) y no cambian.
-- Ejecutar una sola vez.

-- ---- Categorías ----------------------------------------------------
INSERT INTO categoriaProducto (idCategoria, nombreCategoria, descripcion, imagen, activo) VALUES (1, 'Hamburguesas Simples', 'Hamburguesa sencilla con papas y tu salsa a elección.', NULL, 1) ON DUPLICATE KEY UPDATE nombreCategoria=VALUES(nombreCategoria), descripcion=VALUES(descripcion), imagen=NULL, activo=1;
INSERT INTO categoriaProducto (idCategoria, nombreCategoria, descripcion, imagen, activo) VALUES (2, 'Hamburguesas Royal', 'Hamburguesa con huevo frito, papas y tu salsa a elección.', NULL, 1) ON DUPLICATE KEY UPDATE nombreCategoria=VALUES(nombreCategoria), descripcion=VALUES(descripcion), imagen=NULL, activo=1;
INSERT INTO categoriaProducto (idCategoria, nombreCategoria, descripcion, imagen, activo) VALUES (3, 'Hamburguesas Mixtas', 'Hamburguesa con hot dog o tocino, huevo, papas y tu salsa a elección.', NULL, 1) ON DUPLICATE KEY UPDATE nombreCategoria=VALUES(nombreCategoria), descripcion=VALUES(descripcion), imagen=NULL, activo=1;
INSERT INTO categoriaProducto (idCategoria, nombreCategoria, descripcion, imagen, activo) VALUES (4, 'Hamburguesas Hawaianas', 'Hamburguesa con queso, jamón y piña o durazno, papas y tu salsa a elección.', NULL, 1) ON DUPLICATE KEY UPDATE nombreCategoria=VALUES(nombreCategoria), descripcion=VALUES(descripcion), imagen=NULL, activo=1;
INSERT INTO categoriaProducto (idCategoria, nombreCategoria, descripcion, imagen, activo) VALUES (5, 'Hamburguesas a lo Pobre', 'Hamburguesa con huevo y plátano frito, papas y tu salsa a elección.', NULL, 1) ON DUPLICATE KEY UPDATE nombreCategoria=VALUES(nombreCategoria), descripcion=VALUES(descripcion), imagen=NULL, activo=1;
INSERT INTO categoriaProducto (idCategoria, nombreCategoria, descripcion, imagen, activo) VALUES (6, 'Hamburguesas Especiales', 'Hamburguesa con queso, jamón y hot dog o salame, papas y tu salsa a elección.', NULL, 1) ON DUPLICATE KEY UPDATE nombreCategoria=VALUES(nombreCategoria), descripcion=VALUES(descripcion), imagen=NULL, activo=1;
INSERT INTO categoriaProducto (idCategoria, nombreCategoria, descripcion, imagen, activo) VALUES (7, 'Maxi Burgers', 'Las hamburguesas más grandes de la casa, para el hambre de verdad.', NULL, 1) ON DUPLICATE KEY UPDATE nombreCategoria=VALUES(nombreCategoria), descripcion=VALUES(descripcion), imagen=NULL, activo=1;
INSERT INTO categoriaProducto (idCategoria, nombreCategoria, descripcion, imagen, activo) VALUES (8, 'Platos Especiales', 'Salchipapas y platos para compartir.', NULL, 1) ON DUPLICATE KEY UPDATE nombreCategoria=VALUES(nombreCategoria), descripcion=VALUES(descripcion), imagen=NULL, activo=1;
INSERT INTO categoriaProducto (idCategoria, nombreCategoria, descripcion, imagen, activo) VALUES (9, 'Combos', 'Combos que rinden para más de una persona.', NULL, 1) ON DUPLICATE KEY UPDATE nombreCategoria=VALUES(nombreCategoria), descripcion=VALUES(descripcion), imagen=NULL, activo=1;
INSERT INTO categoriaProducto (idCategoria, nombreCategoria, descripcion, imagen, activo) VALUES (10, 'Bebidas', 'Gaseosas, chicha morada y agua, bien heladas.', NULL, 1) ON DUPLICATE KEY UPDATE nombreCategoria=VALUES(nombreCategoria), descripcion=VALUES(descripcion), imagen=NULL, activo=1;
INSERT INTO categoriaProducto (idCategoria, nombreCategoria, descripcion, imagen, activo) VALUES (11, 'Salsas', 'Elige la salsa de tu hamburguesa. No se muestra en la carta pública.', NULL, 1) ON DUPLICATE KEY UPDATE nombreCategoria=VALUES(nombreCategoria), descripcion=VALUES(descripcion), imagen=NULL, activo=1;
INSERT INTO categoriaProducto (idCategoria, nombreCategoria, descripcion, imagen, activo) VALUES (12, 'Papas', 'Elige el tipo de papas de tu hamburguesa. No se muestra en la carta pública.', NULL, 1) ON DUPLICATE KEY UPDATE nombreCategoria=VALUES(nombreCategoria), descripcion=VALUES(descripcion), imagen=NULL, activo=1;
INSERT INTO categoriaProducto (idCategoria, nombreCategoria, descripcion, imagen, activo) VALUES (13, 'Agregados', 'Extras de pago para tu hamburguesa. No se muestra en la carta pública.', NULL, 1) ON DUPLICATE KEY UPDATE nombreCategoria=VALUES(nombreCategoria), descripcion=VALUES(descripcion), imagen=NULL, activo=1;

-- ---- Productos -----------------------------------------------------
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (1, 1, 'Simple de Pollo', 'Hamburguesa de pollo con papas y tu salsa a elección.', 7.00, 30, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (2, 1, 'Simple de Carne', 'Hamburguesa de carne con papas y tu salsa a elección.', 8.50, 30, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (3, 1, 'Simple de Chorizo', 'Hamburguesa de chorizo con papas y tu salsa a elección.', 7.00, 30, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (4, 1, 'Simple de Filete de Pollo', 'Hamburguesa de filete de pollo con papas y tu salsa a elección.', 8.50, 30, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (5, 2, 'Pollo con Huevo', 'Hamburguesa de pollo con huevo frito, papas y tu salsa a elección.', 9.00, 30, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (6, 2, 'Carne con Huevo', 'Hamburguesa de carne con huevo frito, papas y tu salsa a elección.', 10.50, 30, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (7, 2, 'Chorizo con Huevo', 'Hamburguesa de chorizo con huevo frito, papas y tu salsa a elección.', 9.00, 30, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (8, 2, 'Filete de Pollo con Huevo', 'Hamburguesa de filete de pollo con huevo frito, papas y tu salsa a elección.', 10.50, 30, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (9, 3, 'Pollo, Huevo y Hot Dog', 'Hamburguesa de pollo con huevo y hot dog, papas y tu salsa a elección.', 11.00, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (10, 3, 'Carne, Huevo y Hot Dog', 'Hamburguesa de carne con huevo y hot dog, papas y tu salsa a elección.', 12.50, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (11, 3, 'Pollo, Huevo y Tocino', 'Hamburguesa de pollo con huevo y tocino, papas y tu salsa a elección.', 11.00, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (12, 3, 'Carne, Huevo y Tocino', 'Hamburguesa de carne con huevo y tocino, papas y tu salsa a elección.', 12.50, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (13, 3, 'Filete de Pollo, Huevo y Hot Dog', 'Hamburguesa de filete de pollo con huevo y hot dog, papas y tu salsa a elección.', 12.50, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (14, 4, 'Pollo, Queso, Jamón y Piña', 'Hamburguesa hawaiana de pollo con queso, jamón y piña, papas y tu salsa a elección.', 13.00, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (15, 4, 'Carne, Queso, Jamón y Piña', 'Hamburguesa hawaiana de carne con queso, jamón y piña, papas y tu salsa a elección.', 14.50, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (16, 4, 'Pollo, Queso, Jamón y Durazno', 'Hamburguesa hawaiana de pollo con queso, jamón y durazno, papas y tu salsa a elección.', 13.00, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (17, 4, 'Carne, Queso, Jamón y Durazno', 'Hamburguesa hawaiana de carne con queso, jamón y durazno, papas y tu salsa a elección.', 14.50, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (18, 4, 'Filete de Pollo, Queso, Jamón y Piña', 'Hamburguesa hawaiana de filete de pollo con queso, jamón y piña, papas y tu salsa a elección.', 14.50, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (19, 4, 'Filete de Pollo, Queso, Jamón y Durazno', 'Hamburguesa hawaiana de filete de pollo con queso, jamón y durazno, papas y tu salsa a elección.', 14.50, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (20, 5, 'Pollo, Huevo y Plátano', 'Hamburguesa a lo pobre de pollo con huevo y plátano frito, papas y tu salsa a elección.', 11.00, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (21, 5, 'Carne, Huevo y Plátano', 'Hamburguesa a lo pobre de carne con huevo y plátano frito, papas y tu salsa a elección.', 12.50, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (22, 5, 'Filete de Pollo, Huevo y Plátano', 'Hamburguesa a lo pobre de filete de pollo con huevo y plátano frito, papas y tu salsa a elección.', 12.50, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (23, 6, 'Filete de Pollo, Queso, Jamón y Hot Dog', 'Hamburguesa especial de filete de pollo con queso, jamón y hot dog, papas y tu salsa a elección.', 14.50, 20, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (24, 6, 'Filete de Pollo, Queso, Jamón y Salame', 'Hamburguesa especial de filete de pollo con queso, jamón y salame, papas y tu salsa a elección.', 14.50, 20, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (25, 6, 'Pollo, Queso, Jamón y Hot Dog', 'Hamburguesa especial de pollo con queso, jamón y hot dog, papas y tu salsa a elección.', 13.00, 20, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (26, 6, 'Carne, Queso, Jamón y Hot Dog', 'Hamburguesa especial de carne con queso, jamón y hot dog, papas y tu salsa a elección.', 14.50, 20, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (27, 7, 'A lo Pobre Especial Pollo', 'Pollo deshilachado, huevo, plátano, queso, jamón y hot dog.', 17.00, 15, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (28, 7, 'A lo Pobre Especial Carne', 'Carne, huevo, plátano, queso, jamón y hot dog.', 18.50, 15, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (29, 7, 'Carnívora', 'Carne, jamón, queso, chorizo parrillero, tocino y salame.', 18.00, 15, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (30, 7, 'Las Musas', 'Carne o pollo, chorizo, huevo, queso, jamón, hot dog, salame y piña.', 20.00, 15, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (31, 8, 'Salchipapa', 'Papas fritas con hot dog y ensalada.', 12.00, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (32, 8, 'Pollipapa', 'Papas fritas con presa de pollo y ensalada.', 13.00, 25, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (33, 8, 'Salchipollo', 'Papas fritas con presa de pollo, ensalada y hot dog.', 15.00, 20, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (34, 8, 'Salchitodo', 'Chorizo parrillero, huevo, queso, hot dog ahumado, pollo deshilachado, ensalada y papas.', 18.00, 15, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (35, 8, 'Salchimusas', 'Papas, ensalada, chorizo parrillero, hot dog ahumado, tocino y queso derretido. Para 2 personas.', 27.00, 10, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (36, 9, 'Combo Salchimusas', '1 Salchimusas + 2 Chicha Morada.', 30.00, 10, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (37, 10, 'Chicha Morada Natural', '500 ml hecha con 100% ingredientes naturales, sin saborizantes ni preservantes.', 3.00, 50, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (38, 10, 'Agua San Carlos', 'Agua San Carlos 500 ml.', 2.00, 50, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (39, 10, 'Coca-Cola', 'Coca-Cola 600 ml.', 4.00, 50, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (40, 10, 'Inca Kola', 'Inca Kola 600 ml.', 4.00, 50, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (41, 11, 'Mayonesa', 'Salsa clásica para tu hamburguesa.', 0.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (42, 11, 'Ketchup', 'Salsa clásica para tu hamburguesa.', 0.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (43, 11, 'Ají', 'Salsa picante de la casa.', 0.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (44, 11, 'Salsa Golf', 'Mezcla de mayonesa y ketchup.', 0.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (45, 11, 'Aceituna', 'Salsa de aceituna.', 0.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (46, 11, 'Mostaza', 'Salsa clásica para tu hamburguesa.', 0.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (47, 11, 'Tártara', 'Salsa tártara de la casa.', 0.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (48, 12, 'Papas al hilo', 'Papas cortadas finas y crocantes.', 0.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (49, 12, 'Papas Gruesas', 'Papas cortadas gruesas.', 0.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (50, 12, 'Sin papas', 'Tu hamburguesa sin papas.', 0.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (51, 13, 'Hot Dog', 'Agrega un hot dog a tu hamburguesa.', 2.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (52, 13, 'Jamón', 'Agrega jamón a tu hamburguesa.', 2.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (53, 13, 'Piña', 'Agrega piña a tu hamburguesa.', 2.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (54, 13, 'Durazno', 'Agrega durazno a tu hamburguesa.', 2.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (55, 13, 'Plátano', 'Agrega plátano frito a tu hamburguesa.', 2.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (56, 13, 'Salame', 'Agrega salame a tu hamburguesa.', 2.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (57, 13, 'Queso', 'Agrega queso a tu hamburguesa.', 2.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (58, 13, 'Tocino', 'Agrega tocino a tu hamburguesa.', 2.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (59, 13, 'Huevo', 'Agrega un huevo frito a tu hamburguesa.', 2.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;
INSERT INTO producto (idProducto, idCategoria, nombre, descripcion, precio, existencias, imagen, destacado, nota, activo) VALUES (60, 13, 'Presa de Pollo', 'Agrega una presa de pollo a tu hamburguesa.', 6.00, 999, NULL, NULL, NULL, 1) ON DUPLICATE KEY UPDATE idCategoria=VALUES(idCategoria), nombre=VALUES(nombre), descripcion=VALUES(descripcion), precio=VALUES(precio), existencias=VALUES(existencias), imagen=NULL, destacado=NULL, nota=NULL, activo=1;

-- AUTO_INCREMENT al día para que el próximo alta desde el panel no choque
-- (si ya hay filas sueltas por encima de este número, MySQL las respeta).
ALTER TABLE categoriaProducto AUTO_INCREMENT = 14;
ALTER TABLE producto AUTO_INCREMENT = 61;
